version: "3.8"

networks:
  adventure-time-network:
    driver: bridge

services:
  adventure-time.nginx:
    env_file: .env
    restart: always
    container_name: adventure-time.nginx
    ports:
      - ${APP_PORT}:80
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - adventure-time.php
    links:
      - adventure-time.php
    networks:
      - adventure-time-network

  adventure-time.php:
    container_name: adventure-time.php
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/
    restart: always
    networks:
      - adventure-time-network